name: 'Deploy AWS Lambda function'
description: 'Update the code of an AWS Lambda function'
author: "Omri Ildis (on top of Yves Gurcan's work)"
branding:
  icon: 'layers'
  color: 'orange'
inputs:
  function-name:
    description: 'Name of Lambda function'
    required: true
  aws_secret_key:
    description: 'AWS secret key'
    required: true
  aws_access_key_id:
    description: 'AWS access key ID'
    required: true
  aws_region:
    description: 'AWS region of the Lambda'
    required: true
  image_uri:
    description: 'IMAGE URI to use as the lambda container'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
